# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_remove_django_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWorkflowReturning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=10000)),
                ('returned_by_id', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returning', to='workflow.AssessmentWorkflow')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
