# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_expand_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffworkflow',
            name='returned_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
